version: '3'

services:

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379-6379'

  database:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: habit_tracker
    build: .
    env_file: .env
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      database:
          condition: service_healthy

  celery:
    container_name: celery
    build: .
    env_file: .env
    tty: true
    command: bash -c "celery -A config worker -l INFO -P eventlet"
    depends_on:
      - redis
      - app

  celery_beat:
    container_name: celery_beat
    build: .
    env_file: .env
    tty: true
    command: bash -c "celery -A config beat -l INFO -S django"
    depends_on:
      - redis
      - database
      - app
      - celery

volumes:
  pg_data:



